### ISSUE TITLE
Print template line number on ParseTemplate

### ISSUE THREAD

**Issue by tzicatl** [lck/SharpTAL#13]
Is there any switch for SharpTal that allows me to see in which line is it failing to compile the template?

**Comment by lck** [comment]
Hi,

the ParseTemplate method will throw ParseError exception when template contains invalid markup.

Here is the sample code:

Console.WriteLine(new Template(@"<root>
</unexpected_ending_tag>
</root>
").Render(null));

Console output:

Unexpected end tag.

   - String:   "</unexpected_ending_tag>"
   - Filename: <main>
   - Location: (3:0)

Cheers
Roman

**Comment by tzicatl** [comment]
Nice. Thanks
